### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by manitaggarwal** [akanosora/backup#1]
'''
python backup.py -e -c -s /mnt/c/repos/ -t /mnt/d/
''''
I am using this to backup my folder containing git repos and make a tar file. In the 'd' mount

**Comment by zhen-huan-hu** [comment]
Please try “backup.py -s /mnt/c/repos/ -t /mnt/d/”. The -e options is for extracting the content back from a TAR backup file.

**Comment by manitaggarwal** [comment]
I did try “backup.py -s /mnt/c/repos/ -t /mnt/d/”, earlier it did not work.
I found out why such was.
I was using python2. Using python3 and it would work flawlessly.
Now only thing is to do to make a upload the tar file to aws s3 using s3cmd. :)
Thanks.
